cache:
  directories:
    - node_modules
language: node_js
branches:
  only:
  - master
  - dev
install:
  - npm install --no-progress
script:
  - npm test --coverage

after_success:
  - npm prepublish
